// Top 60 companies by market cap
export const topCompanies = [
  { symbol: 'NVDA', name: 'NVIDIA' },
  { symbol: 'AAPL', name: 'Apple' },
  { symbol: 'GOOG', name: 'Alphabet (Google)' },
  { symbol: 'MSFT', name: 'Microsoft' },
  { symbol: 'AMZN', name: 'Amazon' },
  { symbol: 'AVGO', name: 'Broadcom' },
  { symbol: 'META', name: 'Meta Platforms (Facebook)' },
  { symbol: 'TSLA', name: 'Tesla' },
  { symbol: 'BRK-B', name: 'Berkshire Hathaway' },
  { symbol: 'WMT', name: 'Walmart' },
  { symbol: 'LLY', name: 'Eli Lilly' },
  { symbol: 'JPM', name: 'JPMorgan Chase' },
  { symbol: 'XOM', name: 'Exxon Mobil' },
  { symbol: 'V', name: 'Visa' },
  { symbol: 'JNJ', name: 'Johnson & Johnson' },
  { symbol: 'MU', name: 'Micron Technology' },
  { symbol: 'MA', name: 'Mastercard' },
  { symbol: 'COST', name: 'Costco' },
  { symbol: 'ORCL', name: 'Oracle' },
  { symbol: 'CVX', name: 'Chevron' },
  { symbol: 'NFLX', name: 'Netflix' },
  { symbol: 'PLTR', name: 'Palantir' },
  { symbol: 'ABBV', name: 'AbbVie' },
  { symbol: 'BAC', name: 'Bank of America' },
  { symbol: 'CAT', name: 'Caterpillar' },
  { symbol: 'AMD', name: 'AMD' },
  { symbol: 'PG', name: 'Procter & Gamble' },
  { symbol: 'HD', name: 'Home Depot' },
  { symbol: 'KO', name: 'Coca-Cola' },
  { symbol: 'CSCO', name: 'Cisco' },
  { symbol: 'GE', name: 'General Electric' },
  { symbol: 'LRCX', name: 'Lam Research' },
  { symbol: 'AMAT', name: 'Applied Materials' },
  { symbol: 'MRK', name: 'Merck' },
  { symbol: 'MS', name: 'Morgan Stanley' },
  { symbol: 'RTX', name: 'RTX' },
  { symbol: 'PM', name: 'Philip Morris International' },
  { symbol: 'GS', name: 'Goldman Sachs' },
  { symbol: 'UNH', name: 'UnitedHealth' },
  { symbol: 'GEV', name: 'GE Vernova' },
  { symbol: 'WFC', name: 'Wells Fargo' },
  { symbol: 'TMUS', name: 'T-Mobile US' },
  { symbol: 'IBM', name: 'IBM' },
  { symbol: 'INTC', name: 'Intel' },
  { symbol: 'MCD', name: 'McDonald' },
  { symbol: 'VZ', name: 'Verizon' },
  { symbol: 'AXP', name: 'American Express' },
  { symbol: 'PEP', name: 'Pepsico' },
  { symbol: 'KLAC', name: 'KLA' },
  { symbol: 'T', name: 'AT&T' },
  { symbol: 'C', name: 'Citigroup' },
  { symbol: 'NEE', name: 'Nextera Energy' },
  { symbol: 'AMGN', name: 'Amgen' },
  { symbol: 'TMO', name: 'Thermo Fisher Scientific' },
  { symbol: 'ABT', name: 'Abbott Laboratories' },
  { symbol: 'TXN', name: 'Texas Instruments' },
  { symbol: 'TJX', name: 'TJX Companies' },
  { symbol: 'CRM', name: 'Salesforce' },
  { symbol: 'GILD', name: 'Gilead Sciences' },
  { symbol: 'DIS', name: 'Walt Disney' },
]
