// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Stock struct {
	ID int32
}

type StockTrackedStock struct {
	StockID        pgtype.Int4
	TrackedStockID pgtype.Int4
}

type TrackedStock struct {
	ID      int32
	StockID pgtype.Int4
	UserID  pgtype.UUID
}

type User struct {
	ID           pgtype.UUID
	Email        string
	PasswordHash string
}
