// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Stock struct {
	ID     int32
	Symbol string
}

type StockAlert struct {
	ID          int32
	StockID     int32
	UserID      pgtype.UUID
	Condition   string
	TargetPrice float64
	CreatedAt   pgtype.Timestamptz
}

type TrackedStock struct {
	ID        int32
	StockID   int32
	UserID    pgtype.UUID
	CreatedAt pgtype.Timestamptz
}

type User struct {
	ID           pgtype.UUID
	Email        string
	PasswordHash string
}
